export default {
  TOP_TAB_NAVIGATOR: "TopTabNavigation",
  BOTTOM_TAB_NAVIGATOR: "BottomTabNavigation",
  // ORDERS_STACK: "OrderStack",
  // ACCOUNT_STACK: "AccountStack",
  LOGIN_SCREEN: "LoginScreen",
  LOGIN: "Login",
  SIGNUP: "Signup",
  FORGET_PASSWORD: "ForgetPassword",
  OTP_VERIFICATION: "OtpVerification",
  ADD_PHONE_NO: "AddPhoneNo",

  HOME: "Home",
  PRICES: "Prices",
  ORDERS: "Orders",
  ACCOUNT: "Account",
  INVESTMENTS: "Investments",
  MY_WATCH_LIST: "MyWatchlist",
  ALL_COINS: "AllCoins",
  ORDERS_DETAILS: "OrderDetails",
  SECURITY: "Security",
  ACCOUNT_SETTINGS: "Account Settings",
  PRICE_ALERTS: "Price Alerts",
  HELP_AND_SUPPORT: "help and Support",
  CHANGE_LANGUAGE: "Change Language",
  CHANGE_CURRENCY: "Change currency",
  UPDATE_PROFILE: "UpdateProfile",
  PAN_DETAILS: "Pan Details",
  VERIFY_AADHAR: "Verify Aadhar",
  ADD_BANK_ACCOUNT: "Add Bank Account",
  CHANGE_PASSWORD: "Change Password",
  GOOGLE_AUTHENTICATOR: "Google Authenticator",

  PRICE_CHART_DETAILS: "PriceChartDetails",
  SET_PIN: "Set Pin",
  PRICE_CANDLE_CHART: "PriceCandleChart",
  CHECK: "Check",
  CAPTURE_SELFIE: "Capture Selfie",
  PHONE_LOGIN: "Phone Login",
  BUY_SCREEN: "Buy Screen",
  ADD_FUNDS: "Add Funds",
  PAYMENT:"Payment",
  NOTIFICATIONS: "Notifications",
};
